name: Build and deploy to development
on:
  push:
    branches:
      - 'develop'
jobs:
  build_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: cd ./frontend && yarn && cd ../
      - run: npm install -g firebase-tools
      - run: yarn build:frontend
      - run: firebase deploy  --token=$FIREBASE_TOKEN --project mm-content-manager --non-interactive
    env:
      CI: true
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      VUE_APP_BASE_URL: https://mm-content-manager.web.app

