name: Build and deploy to development
on:
  push:
    branches:
      - 'develop'
jobs:
  build_frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.2.0
        name: Checkout repository

      - uses: actions/setup-node@v2.4.0
        name: Setup Node v14
        with:
          node-version: 14

      - run: yarn
        working-directory: frontend
        name: Install dependencies

      - run: npm install -g firebase-tools
        name: Install Firebase tools
        working-directory: frontend

      - run: yarn build --modern
        working-directory: frontend
        name: Build project

      - run: firebase deploy --only hosting:develop  --token=$FIREBASE_TOKEN --project mm-content-manager --non-interactive
        working-directory: frontend
        name: Deploy to firebase hosting
    env:
      CI: true
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      VUE_APP_BASE_URL: https://mm-content-manager.web.app
  build_backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.2.0
        name: Checkout repository

      - uses: actions/setup-node@v2.4.0
        name: Setup Node v10
        with:
          node-version: 10

      - run: yarn
        working-directory: backend
        name: Install dependencies

      - run: npm install -g firebase-tools
        name: Install Firebase tools
        working-directory: backend

      - run: yarn lint
        working-directory: backend
        name: Lint code

      - run: yarn build
        working-directory: backend
        name: Build project

      - run: firebase deploy --only functions --token=$FIREBASE_TOKEN --project mm-content-manager --non-interactive
        working-directory: frontend
        name: Deploy to Firebase functions
    env:
      CI: true
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  deploy_rules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.2.0
        name: Checkout repository

      - uses: actions/setup-node@v2.4.0
        name: Setup Node v14
        with:
          node-version: 14

      - run: npm install -g firebase-tools
        name: Install Firebase tools

      - run: firebase deploy --only database --token=$FIREBASE_TOKEN --project mm-content-manager --non-interactive
        name: Deploy rules to firebase
    env:
      CI: true
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

