name: Verify commits
on:
  push:
    branches:
      - 'feature/**'
      - 'bugfix/**'
      - 'hotfix/**'
      - 'release/**'
      - 'dependabot/**'
jobs:
  build_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.0.1

      - name: Setup Node v14
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn
        working-directory: frontend

      - name: Check code style
        run: yarn lint
        working-directory: frontend

      - name: Build package
        run: yarn build --modern
        working-directory: frontend
  build_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.0.1

      - name: Setup Node v10
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 10

      - name: Install dependencies
        run: yarn
        working-directory: backend

      - name: Check code style
        run: yarn lint
        working-directory: backend

      - name: Build package
        run: yarn build
        working-directory: backend
    env:
      CI: true
